name: "nfl"
version: "1.0.0"
config-version: 2

profile: "nfl"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nfl:
    staging:
      +schema: staging
      +materialized: table
    # intermediate:
    #   +schema: intermediate
    #   +materialized: view
    marts:
      +schema: marts
      +materialized: table

