version: 2

models:
  - name: stg_player_stats_by_game
    description: "Staging model for player-level statistics by game, providing standardized player information and performance metrics."
    columns:
      - name: player_id
        description: "Unique identifier for the player."
      - name: player_name
        description: "Player's display name."
      - name: first_name
        description: "Player's first name."
      - name: last_name
        description: "Player's last name."
      - name: headshot_url
        description: "URL for the player's headshot image."
      - name: jersey_number
        description: "Player's jersey number."
      - name: player_status
        description: "Player’s game status (e.g., active, inactive)."
      - name: status_description_abbr
        description: "Abbreviated status description."
      - name: height
        description: "Player's height in inches."
      - name: player_weight
        description: "Player's weight in pounds."
      - name: age
        description: "Player's age at the time of the game."
      - name: birth_date
        description: "Player's birth date."
      - name: college
        description: "College the player attended."
      - name: years_experience
        description: "Years of experience in the league."
      - name: entry_year
        description: "Year the player entered the league."
      - name: rookie_year
        description: "The player's rookie season."
      - name: draft_team
        description: "Team that drafted the player."
      - name: draft_number
        description: "Draft pick number used to select the player."
      - name: position
        description: "Player's position (e.g., QB, RB, WR, TE)."
      - name: position_group
        description: "High-level position group (e.g., skill players, QBs)."
      - name: team
        description: "The player's team at the time of the game."
      - name: recent_team
        description: "The player's most recent team."
      - name: season
        description: "Season year for these stats."
      - name: season_week
        description: "Week of the season for these stats."
      - name: season_type
        description: "Indicates whether stats are from regular or postseason."
      - name: game_type
        description: "Type of the game (e.g., Regular, Postseason)."
      - name: opponent_team
        description: "Opponent team for that game."
      - name: completions
        description: "Number of completed passes."
      - name: pass_attempts
        description: "Number of pass attempts."
      - name: pass_yards
        description: "Total passing yards."
      - name: passing_air_yards
        description: "Total air yards passed."
      - name: passing_yards_after_catch
        description: "Yards gained after the catch on passing plays."
      - name: passing_first_downs
        description: "First downs earned via passing."
      - name: passing_epa
        description: "Expected points added via passing."
      - name: passing_2pt_conversions
        description: "Number of successful 2-point conversions via pass."
      - name: interceptions
        description: "Number of interceptions thrown."
      - name: pacr
        description: "Passing air conversion ratio (an efficiency metric)."
      - name: dakota
        description: "A proprietary QB performance metric."
      - name: sacks
        description: "Number of times the QB was sacked."
      - name: sack_yards
        description: "Yards lost due to sacks."
      - name: sack_fumbles
        description: "Number of fumbles occurring on sacks."
      - name: sack_fumbles_lost
        description: "Number of sack-related fumbles lost."
      - name: carries
        description: "Number of rushing attempts."
      - name: rushing_yards
        description: "Total rushing yards gained."
      - name: rushing_tds
        description: "Number of rushing touchdowns."
      - name: rushing_fumbles
        description: "Fumbles while rushing."
      - name: rushing_fumbles_lost
        description: "Number of rushing fumbles lost."
      - name: rushing_first_downs
        description: "First downs earned via rushing."
      - name: rushing_epa
        description: "Expected points added via rushing."
      - name: rushing_2pt_conversions
        description: "Number of successful rushing 2-point conversions."
      - name: receptions
        description: "Number of caught passes."
      - name: targets
        description: "Number of times the player was targeted on a pass."
      - name: receiving_yards
        description: "Total yards gained through receptions."
      - name: receiving_tds
        description: "Number of receiving touchdowns."
      - name: receiving_fumbles
        description: "Number of fumbles after a reception."
      - name: receiving_fumbles_lost
        description: "Number of receiving fumbles lost."
      - name: receiving_air_yards
        description: "Air yards attributed to this player's targets."
      - name: receiving_yards_after_catch
        description: "Yards gained after the catch on receptions."
      - name: receiving_first_downs
        description: "First downs earned via receptions."
      - name: receiving_epa
        description: "Expected points added via receiving."
      - name: receiving_2pt_conversions
        description: "Number of successful 2-point conversions via reception."
      - name: racr
        description: "Receiver air conversion ratio (receiving efficiency metric)."
      - name: target_share
        description: "Percentage of team targets this player received."
      - name: air_yards_share
        description: "Percentage of team air yards this player accounted for."
      - name: wopr
        description: "Weighted Opportunity Rating for the player."
      - name: special_teams_tds
        description: "Number of touchdowns scored on special teams."
      - name: fantasy_points
        description: "Standard fantasy football points scored."
      - name: fantasy_points_ppr
        description: "Fantasy points in PPR scoring format."
      - name: espn_id
        description: "Player's ESPN ID."
      - name: sportradar_id
        description: "Player's Sportradar ID."
      - name: yahoo_id
        description: "Player's Yahoo ID."
      - name: rotowire_id
        description: "Player's Rotowire ID."
      - name: pff_id
        description: "Player's Pro Football Focus ID."
      - name: pfr_id
        description: "Player's Pro-Football-Reference ID."
      - name: fantasy_data_id
        description: "Player's FantasyData ID."
      - name: sleeper_id
        description: "Player's Sleeper fantasy platform ID."
      - name: esb_id
        description: "Another external system ID (ESB)."
      - name: gsis_it_id
        description: "NFL GSIS (Game Statistics & Information System) ID."
      - name: smart_id
        description: "A unique identifier used internally or externally."

  - name: stg_combine
    description: "Staging model for nfl contracts."
    columns:
      - name: player_id
        description: "Unique identifier for the player."

  - name: stg_injuries
    description: "Staging model for nfl contracts."
    columns:
      - name: player_id
        description: "Unique identifier for the player."


  - name: stg_contracts
    description: "Staging model for nfl contracts."
    columns:
      - name: player_id
        description: "Unique identifier for the player."

  