version: 2

sources:
  - name: web_scraping
    database: RAMYASHREESHETTY85PLR_ANALYTICS
    schema: STAGING
    tables:
      - name: NFL_SALARIES_2023
        description: "Salaries of NFL players for the 2023 season, scraped from Spotrac."
        columns:
          - name: NAME
            description: "Player's full name."
          - name: TEAM
            description: "Abbreviated team name."
          - name: SALARY
            description: "Player's annual salary in US dollars."
            tests:
              - not_null